#!/usr/bin/env bash
# This script tells the story of each user in the /etc/passwd file.

# Use a while loop to read each line of the /etc/passwd file
while IFS=: read -r username _ userid groupid _ home shell; do
    if [ -n "$username" ]; then
        echo "The user $username is part of the $groupid gang, lives in $home and rides $shell. $userid's place is protected by the passcode x, more info about the user here: $username"
    fi
done < /etc/passwd

