#!/usr/bin/env bash
# This script parses the Apache log file and displays IP and HTTP status code.

# Use awk to extract IP and HTTP status code from the Apache log file
awk '{print $1, $NF}' /home/cee-jay/alx-system_engineering-devops/0x04-loops_conditions_and_parsing/apache-access.log

