#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using a while loop

# Initialize a counter
counter=0

# Define the maximum number of iterations
max_iterations=10

# Use a while loop to display "Best School" while the counter is less than the maximum
while [ $counter -lt $max_iterations ]; do
    echo "Best School"
    
    # Increment the counter
    ((counter++))
done

