#!/usr/bin/env bash
# Start the Docker container with a custom bridge network
docker run -p 8080:80 -d -it --network host holbertonschool/265-0

# Wait for the container to be up and running (adjust sleep time as needed)
sleep 5

# Check if the container is running
if docker ps | grep -q "holbertonschool/265-0"; then
    echo "Docker container is running."
    
    # Test the container by using its IP address
    container_ip="$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' "$(docker ps -q)")"
    curl "$container_ip:8080"
else
    echo "Docker container is not running."
fi

